profiles: prpl.yml: feed_prplos: tr181-dns: fix compilation failure due to a deprecated API in more recent c-ares
Cause: Some APIs in the c-ares library are deprecated in the new version.

` nslookup.c:235:5: error: 'ares_parse_ns_reply' is deprecated: Use ares_dns_parse instead [-Werror=deprecated-declarations]
  235 |     status = ares_parse_ns_reply(abuf, alen, &host);

nslookup.c:350:5: error: 'ares_query' is deprecated: Use ares_query_dnsrec instead [-Werror=deprecated-declarations]
  350 |     ares_query(query->channel, query->domain, C_IN, T_NS, nslookup_ns_cb, query);

nslookup.c:447:9: error: 'ares_get_servers' is deprecated: Use ares_get_servers_csv instead [-Werror=deprecated-declarations]
  447 |         rv = ares_get_servers(query->channel, &server_list); `

Solution: Disable c-ares deprecation for versions ≥ 1.28.0 using the macro CARES_NO_DEPRECATED.

References: PCF-1595

Signed-off-by: Matthias Franck <matthias.franck@softathome.com>